Repository OsmosysSoftware/osmo-x, pull requests merged in 2023-12, with the labels that each got.

#66 refactor: add base consumer class
  apps/api/src/jobs/consumers/notifications/mailgun-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/notification.consumer.ts
  apps/api/src/jobs/consumers/notifications/smtp-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/wa360dialog-notifications.job.consumer.ts
  apps/api/src/jobs/producers/notifications/notifications.job.producer.ts
Labels: ready for review

#79 docs: update documentation content and structure
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  apps/api/LICENSE
  apps/api/README.md
  apps/api/docs/add-new-provider.md
  apps/portal/README.md
Labels: ready for review

#80 fix: mailgun notifications when no attachments provided
  apps/api/src/modules/providers/mailgun/mailgun.service.ts
Labels: ready for review

#84 fix: update mail text/html validation to allow either one or both
  apps/api/src/modules/notifications/dtos/providers/mailgun-data.dto.ts
  apps/api/src/modules/notifications/dtos/providers/smtp-data.dto.ts
Labels: ready for review

#83 feat: make fetch all notifications a public API
  apps/api/src/main.ts
  apps/api/src/modules/notifications/entities/notification.entity.ts
  apps/api/src/modules/notifications/notifications.resolver.ts
Labels: ready for review

#97 build: update typescript-eslint dependencies
  apps/portal/package-lock.json
  apps/portal/package.json
Labels: dependencies, ready for review

#99 docs: add api test cases documentation
  apps/api/README.md
  apps/api/docs/api-test-cases.md
  apps/api/docs/assets/newman-cli-run-results.png
  apps/api/docs/assets/newman-html-report.png
  apps/api/docs/assets/postman-api-run-results.png
Labels: documentation, ready for review
