Repository OsmosysSoftware/osmo-x, pull requests merged in 2024-06, with the labels that each got.

#248 build: bump api dependency package version to latest
  apps/api/docs/channels/sms-Plivo.md
  apps/api/docs/channels/sms-Twilio.md
  apps/api/docs/channels/wa-Twilio-Business.md
  apps/api/docs/channels/wa-Twilio.md
  apps/api/package-lock.json
  apps/api/package.json
Labels: ready for review

#250 build: bump portal dependency package version to latest
  apps/portal/package-lock.json
  apps/portal/package.json
Labels: dependencies, ready for review

#251 feat: add kaps notification in portal
  apps/portal/src/assets/icons/kaps.png
  apps/portal/src/common/constants/notification.ts
Labels: ready for review

#247 feat: add in operator in fetch query core service
  apps/api/src/common/graphql/services/core.service.ts
Labels: ready for review

#254 fix: refactor and update mailgun service to allow different attachment
  apps/api/.env.example
  apps/api/package-lock.json
  apps/api/package.json
  apps/api/src/database/migrations/1718945071282-UpdateDataColumnType.ts
  apps/api/src/main.ts
  apps/api/src/modules/notifications/dtos/providers/mailgun-data.dto.ts
  apps/api/src/modules/providers/mailgun/mailgun.service.ts
Labels: ready for review

#256 docs: add attachment usage for mailgun
  apps/api/docs/channels/mailgun.md
Labels: ready for review

#258 docs: update api usage guide to use x-api-key
  apps/api/docs/usage-guide.md
Labels: ready for review

#257 feat: add graphql api to add new provider and fetch all providers
  apps/api/OsmoX.postman_collection.json
  apps/api/docs/api-documentation.md
  apps/api/src/modules/providers/dto/create-provider.input.ts
  apps/api/src/modules/providers/dto/provider-response.dto.ts
  apps/api/src/modules/providers/providers.module.ts
  apps/api/src/modules/providers/providers.resolver.ts
  apps/api/src/modules/providers/providers.service.ts
Labels: ready for review

#259 docs: remove channeltype from sample request queries
  apps/api/docs/channels/wa-360Dialog.md
  apps/api/docs/channels/wa-Twilio.md
Labels: documentation, ready for review
