Repository OsmosysSoftware/osmo-x, pull requests merged in 2024-11, with the labels that each got.

#351 feat: handle unauthorized error to redirect to login
  apps/portal/src/app/auth/auth.service.ts
  apps/portal/src/app/views/applications/application.model.ts
  apps/portal/src/app/views/applications/applications.service.ts
  apps/portal/src/app/views/notifications/notifications.component.ts
Labels: ready for review

#353 fix: increase logger file maxsize
  apps/api/.env.example
  apps/api/src/config/logger.config.ts
Labels: ready for review

#349 fix: update currentPage, pageSize values for portal
  apps/portal/src/app/views/notifications/notifications.component.ts
Labels: ready for review

#350 fix: reload button event values in portal
  apps/portal/src/app/views/notifications/notifications.component.html
  apps/portal/src/app/views/notifications/notifications.component.ts
Labels: ready for review

#359 fix: update base condition for findAll()
  apps/api/src/modules/applications/applications.service.ts
  apps/api/src/modules/providers/providers.service.ts
Labels: ready for review

#358 build: update api dependencies November 2024
  apps/api/package-lock.json
  apps/api/package.json
Labels: dependencies, ready for review

#357 build: update portal dependencies November 2024
  apps/portal/package-lock.json
  apps/portal/package.json
Labels: dependencies, ready for review

#360 feat: move archiving task to trigger via scheduler script
  apps/api/.env.example
  apps/api/scheduler.sh
  apps/api/src/app.module.ts
  apps/api/src/database/migrations/1730724383210-ArchiveCompletedNotifications.ts
  apps/api/src/modules/applications/entities/application.entity.ts
  apps/api/src/modules/archived-notifications/archived-notifications.controller.spec.ts
  apps/api/src/modules/archived-notifications/archived-notifications.controller.ts
  apps/api/src/modules/archived-notifications/archived-notifications.module.ts
  apps/api/src/modules/archived-notifications/archived-notifications.service.spec.ts
  apps/api/src/modules/archived-notifications/archived-notifications.service.ts
  apps/api/src/modules/archived-notifications/entities/archived-notification.entity.ts
  apps/api/src/modules/providers/entities/provider.entity.ts
Labels: enhancement, ready for review

#363 fix: data types of archived notifications table to match notifications table
  apps/api/src/database/migrations/1732200721350-UpdateArchiveTableDatatypes.ts
Labels: bug, ready for review

#364 chore: bump version to 4.1.1
  apps/api/package-lock.json
  apps/api/package.json
  apps/portal/package-lock.json
  apps/portal/package.json
Labels: dependencies, ready for review

#365 feat: add refresh icon on portal
  apps/portal/package-lock.json
  apps/portal/package.json
  apps/portal/src/app/views/notifications/notifications.component.html
  apps/portal/src/styles.scss
Labels: ready for review

#366 feat: add archived notification toggle
  apps/portal/src/app/views/notifications/notifications.component.html
  apps/portal/src/app/views/notifications/notifications.component.scss
  apps/portal/src/app/views/notifications/notifications.component.ts
Labels: ready for review

#367 feat: findall() function for archived notifications
  apps/api/src/common/graphql/services/core.service.ts
  apps/api/src/modules/archived-notifications/archived-notifications.module.ts
  apps/api/src/modules/archived-notifications/archived-notifications.resolver.spec.ts
  apps/api/src/modules/archived-notifications/archived-notifications.resolver.ts
  apps/api/src/modules/archived-notifications/archived-notifications.service.ts
  apps/api/src/modules/archived-notifications/dtos/archived-notification-response.dto.ts
  apps/api/src/modules/archived-notifications/entities/archived-notification.entity.ts
Labels: ready for review

#368 feat: toggle active/archived notifications on portal
  apps/portal/src/app/graphql/graphql.queries.ts
  apps/portal/src/app/views/notifications/notification.model.ts
  apps/portal/src/app/views/notifications/notifications.component.ts
  apps/portal/src/app/views/notifications/notifications.service.ts
Labels: enhancement, ready for review

#369 docs: update database design
  apps/api/docs/assets/OsmoX_database_schema.erd
  apps/api/docs/assets/OsmoX_database_schema.png
  apps/api/docs/database-design.md
Labels: documentation, ready for review

#370 docs: add archived notification related documentation
  apps/api/OsmoX-API.postman_collection.json
  apps/api/OsmoX.postman_collection.json
  apps/api/docs/api-documentation.md
  apps/api/docs/development-setup.md
  apps/api/docs/production-setup.md
Labels: documentation, ready for review
