Repository OsmosysSoftware/osmo-x, pull requests merged in 2024-08, with the labels that each got.

#297 feat: use aws sdk for javascript v3
  apps/api/docs/channels/push-sns.md
  apps/api/package-lock.json
  apps/api/package.json
  apps/api/src/modules/providers/push-sns/push-sns.service.ts
Labels: enhancement, ready for review

#296 docs: add scripts to postman collection
  apps/api/OsmoX.postman_collection.json
Labels: documentation, ready for review

#300 build: update api dependencies (aug 2024)
  apps/api/docs/channels/mailgun.md
  apps/api/docs/channels/sms-Plivo.md
  apps/api/package-lock.json
  apps/api/package.json
Labels: dependencies, ready for review

#299 build: update portal dependencies (aug 2024)
  apps/portal/package-lock.json
  apps/portal/package.json
Labels: dependencies, ready for review

#292 feat: update pagination to show all notification records in portal
  apps/portal/src/app/graphql/graphql.queries.ts
  apps/portal/src/app/views/notifications/notification.model.ts
  apps/portal/src/app/views/notifications/notifications.component.html
  apps/portal/src/app/views/notifications/notifications.component.scss
  apps/portal/src/app/views/notifications/notifications.component.ts
  apps/portal/src/app/views/notifications/notifications.service.ts
Labels: help wanted, ready for review

#301 chore: update spellings
  apps/api/src/jobs/consumers/notifications/notification.consumer.ts
  apps/api/src/modules/notifications/dtos/providers/vcTwilio-data.dto.ts
  apps/api/src/modules/providers/mailgun/mailgun.service.ts
  apps/api/src/modules/providers/push-sns/push-sns.service.ts
  apps/api/src/modules/providers/sms-kapsystem/sms-kapsystem.service.ts
  apps/api/src/modules/providers/sms-plivo/sms-plivo.service.ts
  apps/api/src/modules/providers/sms-twilio/sms-twilio.service.ts
  apps/api/src/modules/providers/smtp/smtp.service.ts
  apps/api/src/modules/providers/vc-twilio/vc-twilio.service.ts
  apps/api/src/modules/providers/wa-twilio-business/wa-twilio-business.service.ts
  apps/api/src/modules/providers/wa-twilio/wa-twilio.service.ts
Labels: ready for review

#302 feat: mount logs to docker volume
  apps/api/docker-compose.yml
Labels: enhancement, ready for review

#286 feat: update push sns dto
  apps/api/src/modules/notifications/dtos/providers/pushSns-data.dto.ts
Labels: ready for review

#303 fix: add await before any kind of async method call
  apps/api/src/jobs/consumers/notifications/notification.consumer.ts
Labels: ready for review

#304 fix: use identifiable attributes for deletion criteria in database migrations
  apps/api/src/database/migrations/1692870736645-migration.ts
  apps/api/src/database/migrations/1692870736646-seeddata.ts
  apps/api/src/database/migrations/1692870736647-kapsseeddata.ts
  apps/api/src/database/migrations/1720087162842-snsseeddata.ts
  apps/api/src/database/migrations/1721088347000-VoiceCallSeedData.ts
Labels: ready for review

#307 feat: support for notification filter by date in portal
  apps/portal/src/app/app.module.ts
  apps/portal/src/app/views/notifications/notifications.component.html
  apps/portal/src/app/views/notifications/notifications.component.scss
  apps/portal/src/app/views/notifications/notifications.component.ts
Labels: ready for review

#309 chore: improve api pr checklist
  .github/PULL_REQUEST_TEMPLATE/pull_request_template_api.md
Labels: ready for review

#311 feat: move logic for calling webhook to separate queue
  apps/api/src/common/constants/notifications.ts
  apps/api/src/jobs/consumers/notifications/mailgun-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/notification.consumer.ts
  apps/api/src/jobs/consumers/notifications/pushSns-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smsKapsystem-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smsPlivo-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smsTwilio-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smtp-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/vcTwilio-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/wa360dialog-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/waTwilio-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/waTwilioBusiness-notifications.job.consumer.ts
  apps/api/src/modules/notifications/queues/queue.service.ts
  apps/api/src/modules/webhook/webhook.module.ts
  apps/api/src/modules/webhook/webhook.service.ts
Labels: enhancement, ready for review

#313 fix: container start error if missing logs directory
  apps/api/docker-compose.yml
Labels: bug, ready for review

#314 feat: add copy to clipboard on json data
  apps/portal/package-lock.json
  apps/portal/package.json
  apps/portal/src/app/views/notifications/json-dialog/json-dialog.component.html
  apps/portal/src/app/views/notifications/json-dialog/json-dialog.component.spec.ts
  apps/portal/src/app/views/notifications/json-dialog/json-dialog.component.ts
Labels: ready for review
