Repository OsmosysSoftware/osmo-x, pull requests merged in 2024-09, with the labels that each got.

#306 feat: add support for sns sms provider
  apps/api/OsmoX.postman_collection.json
  apps/api/docs/channels/sms-sns.md
  apps/api/src/common/constants/notifications.ts
  apps/api/src/common/decorators/is-data-valid.decorator.ts
  apps/api/src/database/migrations/1723113193873-migration.ts
  apps/api/src/jobs/consumers/notifications/smsSns-notifications.job.consumer.ts
  apps/api/src/modules/notifications/dtos/providers/smsSns-data.dto.ts
  apps/api/src/modules/notifications/notifications.module.ts
  apps/api/src/modules/notifications/queues/queue.service.ts
  apps/api/src/modules/providers/sms-sns/sms-sns.module.ts
  apps/api/src/modules/providers/sms-sns/sms-sns.service.spec.ts
  apps/api/src/modules/providers/sms-sns/sms-sns.service.ts
Labels: ready for review

#308 feat: update mailgun response and store retry attempt in separate table
  apps/api/src/database/migrations/1723401906112-AddRetryTable.ts
  apps/api/src/jobs/consumers/notifications/mailgun-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/notification.consumer.ts
  apps/api/src/jobs/consumers/notifications/pushSns-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smsKapsystem-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smsPlivo-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smsSns-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smsTwilio-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smtp-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/vcTwilio-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/wa360dialog-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/waTwilio-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/waTwilioBusiness-notifications.job.consumer.ts
  apps/api/src/modules/notifications/entities/notification.entity.ts
  apps/api/src/modules/notifications/entities/retry-notification.entity.ts
  apps/api/src/modules/notifications/notifications.module.ts
  apps/api/src/modules/notifications/notifications.service.ts
  apps/api/src/modules/providers/mailgun/mailgun.service.ts
Labels: ready for review

#312 feat: add search notifier field
  apps/portal/src/app/views/notifications/notifications.component.html
  apps/portal/src/app/views/notifications/notifications.component.scss
  apps/portal/src/app/views/notifications/notifications.component.ts
Labels: enhancement, ready for review

#328 docs: update env values in setup
  apps/api/docs/development-setup.md
  apps/api/docs/production-setup.md
Labels: documentation, ready for review

#330 feat: update auth guard code
  apps/api/.env.example
  apps/api/package-lock.json
  apps/api/package.json
  apps/api/src/common/constants/jwtInterface.ts
  apps/api/src/common/guards/api-key/auth.guard.ts
  apps/api/src/common/guards/api-key/gql-auth.guard.ts
  apps/api/src/modules/applications/applications.module.ts
  apps/api/src/modules/applications/applications.resolver.ts
  apps/api/src/modules/applications/applications.service.ts
  apps/api/src/modules/auth/auth.module.ts
  apps/api/src/modules/auth/auth.service.ts
  apps/api/src/modules/auth/dto/login-response.ts
  apps/api/src/modules/auth/strategies/jwt.strategy.ts
  apps/api/src/modules/auth/strategies/local.strategy.ts
  apps/api/src/modules/notifications/notifications.module.ts
  apps/api/src/modules/notifications/notifications.resolver.ts
  apps/api/src/modules/notifications/notifications.service.ts
  apps/api/src/modules/providers/providers.module.ts
  apps/api/src/modules/providers/providers.resolver.ts
  apps/api/src/modules/webhook/webhook.resolver.ts
Labels: ready for review

#333 docs: update block diagram
  apps/api/docs/assets/OsmoX-block-diagram.drawio
  apps/api/docs/assets/OsmoX-block-diagram.png
Labels: documentation, ready for review

#331 feat: add encryption for api keys
  apps/api/src/common/guards/api-key/api-key.guard.ts
  apps/api/src/common/utils/bcrypt.ts
  apps/api/src/database/migrations/1727156770079-AddMaskedKeyColumn.ts
  apps/api/src/modules/server-api-keys/entities/server-api-key.entity.ts
  apps/api/src/modules/server-api-keys/server-api-keys.module.ts
  apps/api/src/modules/server-api-keys/server-api-keys.resolver.ts
  apps/api/src/modules/server-api-keys/server-api-keys.service.ts
Labels: ready for review

#329 docs: add postman api and environment collection, update setup
  apps/api/OsmoX-API.postman_collection.json
  apps/api/OsmoX-API.postman_environment.json
  apps/api/OsmoX.postman_collection.json
  apps/api/docs/api-documentation.md
  apps/api/docs/development-setup.md
  apps/api/docs/production-setup.md
Labels: documentation, ready for review

#334 docs: ensure the document/api collection is in sync with the current work
  apps/api/.env.example
  apps/api/OsmoX.postman_collection.json
  apps/api/docs/api-documentation.md
  apps/api/docs/development-setup.md
  apps/api/docs/production-setup.md
Labels: documentation, ready for review

#332 feat: update portal for handling JWT Token API changes
  apps/portal/src/app/graphql/graphql.queries.ts
  apps/portal/src/app/views/applications/application.model.ts
  apps/portal/src/app/views/applications/applications.service.ts
  apps/portal/src/app/views/notifications/notifications.component.html
  apps/portal/src/app/views/notifications/notifications.component.ts
  apps/portal/src/common/constants/notification.ts
Labels: ready for review

#305 feat: add support for aws ses
  apps/api/docs/channels/aws-ses.md
  apps/api/docs/usage-guide.md
  apps/api/package-lock.json
  apps/api/package.json
  apps/api/src/common/constants/notifications.ts
  apps/api/src/common/decorators/is-data-valid.decorator.ts
  apps/api/src/common/decorators/is-string-or-stringarray.decorator.ts
  apps/api/src/database/migrations/1722988740000-AwsSesSeedData.ts
  apps/api/src/jobs/consumers/notifications/awsSes-notifications.job.consumer.ts
  apps/api/src/modules/notifications/dtos/providers/awsSes-data.dto.ts
  apps/api/src/modules/notifications/notifications.module.ts
  apps/api/src/modules/notifications/queues/queue.service.ts
  apps/api/src/modules/providers/aws-ses/aws-ses.module.ts
  apps/api/src/modules/providers/aws-ses/aws-ses.service.spec.ts
  apps/api/src/modules/providers/aws-ses/aws-ses.service.ts
Labels: ready for review
