Repository OsmosysSoftware/osmo-x, pull requests merged in 2024-07, with the labels that each got.

#264 feat: add support for dynamic provider queues
  apps/api/.env.example
  apps/api/package-lock.json
  apps/api/package.json
  apps/api/src/app.module.ts
  apps/api/src/jobs/consumers/notifications/mailgun-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/notification.consumer.ts
  apps/api/src/jobs/consumers/notifications/smsKapsystem-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smsPlivo-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smsTwilio-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smtp-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/wa360dialog-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/waTwilio-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/waTwilioBusiness-notifications.job.consumer.ts
  apps/api/src/jobs/producers/notifications/notifications.job.producer.ts
  apps/api/src/modules/notifications/notifications.module.ts
  apps/api/src/modules/notifications/queues/mailgun.queue.ts
  apps/api/src/modules/notifications/queues/queue.service.ts
  apps/api/src/modules/notifications/queues/smsKapsystem.queue.ts
  apps/api/src/modules/notifications/queues/smsPlivo.queue.ts
  apps/api/src/modules/notifications/queues/smsTwilio.queue.ts
  apps/api/src/modules/notifications/queues/smtp.queue.ts
  apps/api/src/modules/notifications/queues/wa360dialog.queue.ts
  apps/api/src/modules/notifications/queues/waTwilio.queue.ts
  apps/api/src/modules/notifications/queues/waTwilioBusiness.queue.ts
Labels: enhancement, ready for review

#263 feat: add retry and delivery confirmation for wa twilio
  apps/api/.env.example
  apps/api/.gitignore
  apps/api/src/common/constants/notifications.ts
  apps/api/src/database/migrations/1719299457601-AddRetryCountColumn.ts
  apps/api/src/database/migrations/1719335040819-UpdateDeliveryStatusValues.ts
  apps/api/src/jobs/consumers/notifications/mailgun-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/notification.consumer.ts
  apps/api/src/jobs/consumers/notifications/smsKapsystem-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smsPlivo-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smsTwilio-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smtp-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/wa360dialog-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/waTwilio-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/waTwilioBusiness-notifications.job.consumer.ts
  apps/api/src/jobs/producers/notifications/notifications.job.producer.ts
  apps/api/src/modules/notifications/entities/notification.entity.ts
  apps/api/src/modules/notifications/notifications.service.ts
  apps/api/src/modules/notifications/queues/queue.service.ts
  apps/api/src/modules/notifications/schedule/schedule.service.ts
  apps/api/src/modules/providers/wa-twilio/wa-twilio.service.ts
Labels: ready for review

#266 feat: add retry for kaps system
  apps/api/src/common/constants/notifications.ts
Labels: ready for review

#265 feat: add retry and delivery confirmation for wa twilio business
  apps/api/src/common/constants/notifications.ts
  apps/api/src/jobs/consumers/notifications/waTwilioBusiness-notifications.job.consumer.ts
  apps/api/src/modules/notifications/queues/queue.service.ts
  apps/api/src/modules/providers/wa-twilio-business/wa-twilio-business.service.ts
Labels: enhancement, ready for review

#268 feat: add retry for 360dialog
  apps/api/src/common/constants/notifications.ts
Labels: ready for review

#262 feat: add retry and delivery confirmation for mailgun
  apps/api/.env.example
  apps/api/src/common/constants/notifications.ts
  apps/api/src/jobs/consumers/notifications/mailgun-notifications.job.consumer.ts
  apps/api/src/modules/notifications/queues/queue.service.ts
  apps/api/src/modules/providers/mailgun/mailgun.service.ts
Labels: ready for review

#261 feat: add retry and delivery confirmation for plivo
  apps/api/src/common/constants/notifications.ts
  apps/api/src/jobs/consumers/notifications/smsPlivo-notifications.job.consumer.ts
  apps/api/src/modules/notifications/queues/queue.service.ts
  apps/api/src/modules/providers/sms-plivo/sms-plivo.service.ts
Labels: ready for review

#269 feat: add support for push notification using sns
  apps/api/package-lock.json
  apps/api/package.json
  apps/api/src/common/constants/database.ts
  apps/api/src/common/constants/notifications.ts
  apps/api/src/common/decorators/is-data-valid.decorator.ts
  apps/api/src/database/migrations/1720087162842-snsseeddata.ts
  apps/api/src/jobs/consumers/notifications/pushSns-notifications.job.consumer.ts
  apps/api/src/modules/notifications/dtos/providers/pushSns-data.dto.ts
  apps/api/src/modules/notifications/notifications.module.ts
  apps/api/src/modules/notifications/queues/queue.service.ts
  apps/api/src/modules/providers/providers.module.ts
  apps/api/src/modules/providers/push-sns/push-sns.module.ts
  apps/api/src/modules/providers/push-sns/push-sns.service.spec.ts
  apps/api/src/modules/providers/push-sns/push-sns.service.ts
Labels: ready for review

#271 build: update api dependencies to latest version
  apps/api/docs/channels/sms-Twilio.md
  apps/api/docs/channels/smtp.md
  apps/api/docs/channels/wa-Twilio-Business.md
  apps/api/docs/channels/wa-Twilio.md
  apps/api/package-lock.json
  apps/api/package.json
Labels: documentation, dependencies, ready for review

#275 feat: update delivery status values in portal
  apps/portal/src/app/views/notifications/notifications.component.scss
  apps/portal/src/app/views/notifications/notifications.component.ts
  apps/portal/src/common/constants/notification.ts
Labels: ready for review

#276 feat: display sns provider & icon in portal
  apps/portal/src/app/views/notifications/notifications.component.scss
  apps/portal/src/assets/icons/aws.png
  apps/portal/src/assets/icons/pushnotification.svg
  apps/portal/src/common/constants/notification.ts
Labels: ready for review

#277 fix: add smtp in skip confirmation list
  apps/api/src/common/constants/notifications.ts
Labels: ready for review

#280 refactor: wrap code in block scope inside switch
  apps/api/src/common/decorators/is-data-valid.decorator.ts
Labels: ready for review

#279 feat: resolve caching issues for new changes in portal
  apps/portal/nginx.conf
Labels: ready for review

#270 docs: update document for push notification support
  apps/api/OsmoX.postman_collection.json
  apps/api/docs/channels/push-sns.md
  apps/api/docs/usage-guide.md
Labels: ready for review

#274 docs: add usage guide for sns
  apps/api/docs/sns-usage-guide.md
Labels: ready for review

#278 feat: add webhook support for provider
  apps/api/OsmoX.postman_collection.json
  apps/api/src/app.module.ts
  apps/api/src/database/migrations/1720458965605-AddWebhookTable.ts
  apps/api/src/jobs/consumers/notifications/mailgun-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/notification.consumer.ts
  apps/api/src/jobs/consumers/notifications/pushSns-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smsKapsystem-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smsPlivo-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smsTwilio-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/smtp-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/wa360dialog-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/waTwilio-notifications.job.consumer.ts
  apps/api/src/jobs/consumers/notifications/waTwilioBusiness-notifications.job.consumer.ts
  apps/api/src/modules/notifications/notifications.module.ts
  apps/api/src/modules/webhook/dto/create-webhook.input.ts
  apps/api/src/modules/webhook/entities/webhook.entity.ts
  apps/api/src/modules/webhook/webhook.module.ts
  apps/api/src/modules/webhook/webhook.resolver.ts
  apps/api/src/modules/webhook/webhook.service.spec.ts
  apps/api/src/modules/webhook/webhook.service.ts
Labels: ready for review

#281 docs: add webhook guide
  apps/api/docs/webhook-guide.md
Labels: ready for review

#282 chore: exit with error status for warnings in lint
  apps/api/package.json
Labels: ready for review

#283 feat: add support for twilio voice call
  apps/api/src/common/constants/database.ts
  apps/api/src/common/constants/notifications.ts
  apps/api/src/common/decorators/is-data-valid.decorator.ts
  apps/api/src/database/migrations/1721088347000-VoiceCallSeedData.ts
  apps/api/src/jobs/consumers/notifications/vcTwilio-notifications.job.consumer.ts
  apps/api/src/modules/notifications/dtos/providers/vcTwilio-data.dto.ts
  apps/api/src/modules/notifications/notifications.module.ts
  apps/api/src/modules/notifications/queues/queue.service.ts
  apps/api/src/modules/providers/vc-twilio/vc-twilio.module.ts
  apps/api/src/modules/providers/vc-twilio/vc-twilio.service.spec.ts
  apps/api/src/modules/providers/vc-twilio/vc-twilio.service.ts
Labels: ready for review

#287 docs: fix mailgun attachment field values
  apps/api/docs/channels/mailgun.md
Labels: documentation, ready for review

#288 feat: display voice call provider & icon in portal
  apps/portal/src/app/views/notifications/notifications.component.scss
  apps/portal/src/assets/icons/voicecall.svg
  apps/portal/src/common/constants/notification.ts
Labels: ready for review

#285 fix: issue with webhook called repeatedly
  apps/api/src/jobs/consumers/notifications/notification.consumer.ts
  apps/api/src/modules/notifications/notifications.service.ts
Labels: ready for review

#284 feat: return proper status code for database error
  apps/api/src/app.module.ts
  apps/api/src/database/database-error.interceptor.spec.ts
  apps/api/src/database/database-error.interceptor.ts
  apps/api/src/modules/notifications/notifications.controller.ts
Labels: ready for review

#290 fix: error objects and storing in result in db
  apps/api/src/jobs/consumers/notifications/notification.consumer.ts
  apps/api/src/modules/notifications/notifications.service.ts
Labels: bug, ready for review

#291 feat: hide applicationId, providerId from portal
  apps/portal/src/app/graphql/graphql.queries.ts
  apps/portal/src/app/views/notifications/notification.model.ts
  apps/portal/src/app/views/notifications/notifications.component.html
Labels: ready for review

#294 feat: add debug logs in api
  apps/api/.env.example
  apps/api/src/common/decorators/is-data-valid.decorator.ts
  apps/api/src/common/guards/api-key/api-key.guard.ts
  apps/api/src/config/logger.config.ts
  apps/api/src/jobs/consumers/notifications/notification.consumer.ts
  apps/api/src/jobs/producers/notifications/notifications.job.producer.ts
  apps/api/src/modules/notifications/notifications.controller.ts
  apps/api/src/modules/notifications/notifications.service.ts
  apps/api/src/modules/notifications/queues/queue.service.ts
  apps/api/src/modules/providers/mailgun/mailgun.module.ts
  apps/api/src/modules/providers/mailgun/mailgun.service.ts
  apps/api/src/modules/providers/providers.service.ts
  apps/api/src/modules/providers/push-sns/push-sns.module.ts
  apps/api/src/modules/providers/push-sns/push-sns.service.ts
  apps/api/src/modules/providers/sms-kapsystem/sms-kapsystem.module.ts
  apps/api/src/modules/providers/sms-kapsystem/sms-kapsystem.service.ts
  apps/api/src/modules/providers/sms-plivo/sms-plivo.module.ts
  apps/api/src/modules/providers/sms-plivo/sms-plivo.service.ts
  apps/api/src/modules/providers/sms-twilio/sms-twilio.module.ts
  apps/api/src/modules/providers/sms-twilio/sms-twilio.service.ts
  apps/api/src/modules/providers/smtp/smtp.module.ts
  apps/api/src/modules/providers/smtp/smtp.service.ts
  apps/api/src/modules/providers/vc-twilio/vc-twilio.module.ts
  apps/api/src/modules/providers/vc-twilio/vc-twilio.service.ts
  apps/api/src/modules/providers/wa-twilio-business/wa-twilio-business.module.ts
  apps/api/src/modules/providers/wa-twilio-business/wa-twilio-business.service.ts
  apps/api/src/modules/providers/wa-twilio/wa-twilio.module.ts
  apps/api/src/modules/providers/wa-twilio/wa-twilio.service.ts
  apps/api/src/modules/providers/wa360dialog/wa360dialog.module.ts
  apps/api/src/modules/providers/wa360dialog/wa360dialog.service.ts
Labels: ready for review

#293 feat: move scheduler logic to separate script
  apps/api/Dockerfile
  apps/api/scheduler.sh
  apps/api/src/modules/notifications/notifications.controller.ts
  apps/api/src/modules/notifications/schedule/schedule.service.ts
Labels: enhancement, ready for review
